/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.aliyun.resource.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AliYunResourceErrorCode implements org.apache.thrift.TEnum {
  REQUEST_ECS_INSTANCES_FAIL(1001);

  private final int value;

  private AliYunResourceErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AliYunResourceErrorCode findByValue(int value) { 
    switch (value) {
      case 1001:
        return REQUEST_ECS_INSTANCES_FAIL;
      default:
        return null;
    }
  }
}
