/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.aliyun.resource.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 阿里云实例付费方式
 */
public enum InstanceChargeType implements org.apache.thrift.TEnum {
  PREPAID(0),
  POSTPAID(1);

  private final int value;

  private InstanceChargeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static InstanceChargeType findByValue(int value) { 
    switch (value) {
      case 0:
        return PREPAID;
      case 1:
        return POSTPAID;
      default:
        return null;
    }
  }
}
