/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.aliyun.resource.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SynceEcsInstanceOption implements org.apache.thrift.TBase<SynceEcsInstanceOption, SynceEcsInstanceOption._Fields>, java.io.Serializable, Cloneable, Comparable<SynceEcsInstanceOption> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SynceEcsInstanceOption");

  private static final org.apache.thrift.protocol.TField INSTANCE_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("instanceIds", org.apache.thrift.protocol.TType.SET, (short)1);
  private static final org.apache.thrift.protocol.TField REGION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("regionId", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SynceEcsInstanceOptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SynceEcsInstanceOptionTupleSchemeFactory());
  }

  public Set<String> instanceIds; // optional
  public String regionId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INSTANCE_IDS((short)1, "instanceIds"),
    REGION_ID((short)2, "regionId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INSTANCE_IDS
          return INSTANCE_IDS;
        case 2: // REGION_ID
          return REGION_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.INSTANCE_IDS,_Fields.REGION_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INSTANCE_IDS, new org.apache.thrift.meta_data.FieldMetaData("instanceIds", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.REGION_ID, new org.apache.thrift.meta_data.FieldMetaData("regionId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SynceEcsInstanceOption.class, metaDataMap);
  }

  public SynceEcsInstanceOption() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SynceEcsInstanceOption(SynceEcsInstanceOption other) {
    if (other.isSetInstanceIds()) {
      Set<String> __this__instanceIds = new HashSet<String>(other.instanceIds);
      this.instanceIds = __this__instanceIds;
    }
    if (other.isSetRegionId()) {
      this.regionId = other.regionId;
    }
  }

  public SynceEcsInstanceOption deepCopy() {
    return new SynceEcsInstanceOption(this);
  }

  @Override
  public void clear() {
    this.instanceIds = null;
    this.regionId = null;
  }

  public int getInstanceIdsSize() {
    return (this.instanceIds == null) ? 0 : this.instanceIds.size();
  }

  public java.util.Iterator<String> getInstanceIdsIterator() {
    return (this.instanceIds == null) ? null : this.instanceIds.iterator();
  }

  public void addToInstanceIds(String elem) {
    if (this.instanceIds == null) {
      this.instanceIds = new HashSet<String>();
    }
    this.instanceIds.add(elem);
  }

  public Set<String> getInstanceIds() {
    return this.instanceIds;
  }

  public SynceEcsInstanceOption setInstanceIds(Set<String> instanceIds) {
    this.instanceIds = instanceIds;
    return this;
  }

  public void unsetInstanceIds() {
    this.instanceIds = null;
  }

  /** Returns true if field instanceIds is set (has been assigned a value) and false otherwise */
  public boolean isSetInstanceIds() {
    return this.instanceIds != null;
  }

  public void setInstanceIdsIsSet(boolean value) {
    if (!value) {
      this.instanceIds = null;
    }
  }

  public String getRegionId() {
    return this.regionId;
  }

  public SynceEcsInstanceOption setRegionId(String regionId) {
    this.regionId = regionId;
    return this;
  }

  public void unsetRegionId() {
    this.regionId = null;
  }

  /** Returns true if field regionId is set (has been assigned a value) and false otherwise */
  public boolean isSetRegionId() {
    return this.regionId != null;
  }

  public void setRegionIdIsSet(boolean value) {
    if (!value) {
      this.regionId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INSTANCE_IDS:
      if (value == null) {
        unsetInstanceIds();
      } else {
        setInstanceIds((Set<String>)value);
      }
      break;

    case REGION_ID:
      if (value == null) {
        unsetRegionId();
      } else {
        setRegionId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INSTANCE_IDS:
      return getInstanceIds();

    case REGION_ID:
      return getRegionId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INSTANCE_IDS:
      return isSetInstanceIds();
    case REGION_ID:
      return isSetRegionId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SynceEcsInstanceOption)
      return this.equals((SynceEcsInstanceOption)that);
    return false;
  }

  public boolean equals(SynceEcsInstanceOption that) {
    if (that == null)
      return false;

    boolean this_present_instanceIds = true && this.isSetInstanceIds();
    boolean that_present_instanceIds = true && that.isSetInstanceIds();
    if (this_present_instanceIds || that_present_instanceIds) {
      if (!(this_present_instanceIds && that_present_instanceIds))
        return false;
      if (!this.instanceIds.equals(that.instanceIds))
        return false;
    }

    boolean this_present_regionId = true && this.isSetRegionId();
    boolean that_present_regionId = true && that.isSetRegionId();
    if (this_present_regionId || that_present_regionId) {
      if (!(this_present_regionId && that_present_regionId))
        return false;
      if (!this.regionId.equals(that.regionId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SynceEcsInstanceOption other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetInstanceIds()).compareTo(other.isSetInstanceIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInstanceIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.instanceIds, other.instanceIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRegionId()).compareTo(other.isSetRegionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRegionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.regionId, other.regionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SynceEcsInstanceOption(");
    boolean first = true;

    if (isSetInstanceIds()) {
      sb.append("instanceIds:");
      if (this.instanceIds == null) {
        sb.append("null");
      } else {
        sb.append(this.instanceIds);
      }
      first = false;
    }
    if (isSetRegionId()) {
      if (!first) sb.append(", ");
      sb.append("regionId:");
      if (this.regionId == null) {
        sb.append("null");
      } else {
        sb.append(this.regionId);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SynceEcsInstanceOptionStandardSchemeFactory implements SchemeFactory {
    public SynceEcsInstanceOptionStandardScheme getScheme() {
      return new SynceEcsInstanceOptionStandardScheme();
    }
  }

  private static class SynceEcsInstanceOptionStandardScheme extends StandardScheme<SynceEcsInstanceOption> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SynceEcsInstanceOption struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INSTANCE_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set0 = iprot.readSetBegin();
                struct.instanceIds = new HashSet<String>(2*_set0.size);
                for (int _i1 = 0; _i1 < _set0.size; ++_i1)
                {
                  String _elem2;
                  _elem2 = iprot.readString();
                  struct.instanceIds.add(_elem2);
                }
                iprot.readSetEnd();
              }
              struct.setInstanceIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REGION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.regionId = iprot.readString();
              struct.setRegionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SynceEcsInstanceOption struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.instanceIds != null) {
        if (struct.isSetInstanceIds()) {
          oprot.writeFieldBegin(INSTANCE_IDS_FIELD_DESC);
          {
            oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, struct.instanceIds.size()));
            for (String _iter3 : struct.instanceIds)
            {
              oprot.writeString(_iter3);
            }
            oprot.writeSetEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.regionId != null) {
        if (struct.isSetRegionId()) {
          oprot.writeFieldBegin(REGION_ID_FIELD_DESC);
          oprot.writeString(struct.regionId);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SynceEcsInstanceOptionTupleSchemeFactory implements SchemeFactory {
    public SynceEcsInstanceOptionTupleScheme getScheme() {
      return new SynceEcsInstanceOptionTupleScheme();
    }
  }

  private static class SynceEcsInstanceOptionTupleScheme extends TupleScheme<SynceEcsInstanceOption> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SynceEcsInstanceOption struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetInstanceIds()) {
        optionals.set(0);
      }
      if (struct.isSetRegionId()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetInstanceIds()) {
        {
          oprot.writeI32(struct.instanceIds.size());
          for (String _iter4 : struct.instanceIds)
          {
            oprot.writeString(_iter4);
          }
        }
      }
      if (struct.isSetRegionId()) {
        oprot.writeString(struct.regionId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SynceEcsInstanceOption struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TSet _set5 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.instanceIds = new HashSet<String>(2*_set5.size);
          for (int _i6 = 0; _i6 < _set5.size; ++_i6)
          {
            String _elem7;
            _elem7 = iprot.readString();
            struct.instanceIds.add(_elem7);
          }
        }
        struct.setInstanceIdsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.regionId = iprot.readString();
        struct.setRegionIdIsSet(true);
      }
    }
  }

}

